name: NodeJS build and push
permissions:
    contents: write 
    
on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    
    - uses: actions/checkout@v3
    - name: Push to gh-pages
      run: |
       git config --global user.name 'Ayush Deshpande'
       git config --global user.email 'asyncdoggo@users.noreply.github.com'
       ls
       npx gh-pages -d dist -b gh-pages
          
